# Generated by Django 4.0.3 on 2022-04-24 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='desciption',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='description', verbose_name='description'),
            preserve_default=False,
        ),
    ]
