# Generated by Django 4.0.3 on 2022-04-30 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_alter_post_category'),
        ('favorites', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='post',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='posts.post'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_favorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
