# Generated by Django 4.0.3 on 2022-06-01 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=155, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='phone number')),
                ('address', models.CharField(max_length=1000)),
                ('avatar', models.ImageField(default='user/avatar.png', upload_to='avatar/<django.db.models.fields.CharField>/')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('joined_date', models.DateTimeField(auto_now_add=True, verbose_name='date join')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='otp')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
