# Generated by Django 4.0.3 on 2022-05-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='otp'),
        ),
    ]
