# Generated by Django 4.0.3 on 2022-06-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='country',
        ),
    ]
